language: python
sudo: true
dist: xenial
python:
  - "3.6"

install:
  - git clone https://github.com/MasterOdin/vpnc vpnc
  - sudo bash setup_vpnc.sh
  - pushd vpnc
  - docker build -t vpnc:latest .
  - docker run -t -d --privileged --name vpnc vpnc:latest
  - docker exec -it vpnc curl https://canihazip.com/s
  - docker exec -it vpnc curl https://internal.cisl.rpi.edu